# SPDX-FileCopyrightText: 2021 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Run tests & build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.job }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16', '18' ]
    name: Test and build with NodeJS ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup node
        uses: ./.github/actions/setup-node
        with:
          NODEJS_VERSION: ${{ matrix.node }}

      - name: Test Project
        uses: ./.github/actions/non-writing-turbo-task
        with:
          TASK_NAME: test:ci
          NODEJS_VERSION: ${{ matrix.node }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: Build project
        run: yarn build
        env:
          NODEJS_VERSION: ${{ matrix.node }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
